- name: nginx install and run
  hosts: all
  become: yes  #take sudo access
  # vars_files:
  # - /var/expense/credentials_03-nginx.yaml

  tasks:
  - name: install nginx
    ansible.builtin.package: #heterogenous module that can work for all distributors
      name: nginx
      state: present

  - name: nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes